name: Deploy to Github Pages
on:
  push:
    branches:
      - master

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Create Node Environment
        uses: actions/setup-node@v1
        with:
          node-version: 18.12.1
      - name: Install Packages
        run:
          npm install
      - name: Build Application
        run:
          npm run build
      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v1
        with:
          path: _/site
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
